name: chaz
favicon: null
layout_spectrum: 0.186255834531039
typography_spectrum: 0.6322285942733288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6423648693598807
  lightness: 0.4634366570971906
  saturation: 0.5307317860424519
  rhythmicContrast: 0.7046155591960996
purpose: []
