name: chaz
favicon: null
layout_spectrum: 0.35268
typography_spectrum: 0.40514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.7046155591960996
purpose: []
